apiVersion: v1
kind: Service
metadata:
  name: {{ include "platform-assistant.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "platform-assistant.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "platform-assistant.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.gateway.port }}